import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");
const read=(p)=>fs.readFileSync(path.join(ROOT,p),"utf8");
const req=["README.md","START_HERE.md","package.json","package-lock.json","tsconfig.json","mcp-client.mjs","dataset/place.schema.json","dataset/entity-field-policy.json","dataset/source_policy.json","dataset/brand_voice.md","dataset/iran-cpi.schema.json","prompts/01-start-province.txt","prompts/02-run-scope.txt","prompts/03-resume.txt","prompts/04-repair-entity.txt","prompts/05-final-audit-minify.txt","prompts/README.md","taxonomy/types.json","taxonomy/subtypes.json","taxonomy/categories.json","taxonomy/activities.json","taxonomy/features.json","taxonomy/facilities.json","taxonomy/risks.json","taxonomy/agent-taxonomy/proposals.json","src/taxonomy.ts"];
for(const f of req) if(!fs.existsSync(path.join(ROOT,f))) throw new Error(`Missing required file: ${f}`);
for(const f of ["node_modules","dist","output","tests"]) if(fs.existsSync(path.join(ROOT,f))) throw new Error(`Unwanted packaged directory: ${f}`);
for(let i=1;i<=31;i++) JSON.parse(read(`input/${i}.json`));
const t=Object.fromEntries(["types","subtypes","categories","activities","features","facilities","risks"].map(d=>{const x=JSON.parse(read(`taxonomy/${d}.json`)); if(!Array.isArray(x.items)) throw new Error(`${d} missing items`); const ids=x.items.map(i=>i.id); if(new Set(ids).size!==ids.length) throw new Error(`duplicate ids in ${d}`); return [d,ids.length];}));
const schema=JSON.parse(read("dataset/place.schema.json"));
if("tags" in schema.properties) throw new Error("tags must not exist");
if("emergencyNumbers" in schema.properties.safety.properties) throw new Error("emergencyNumbers must not exist");
if("distanceKm" in schema.$defs.transportNode.properties) throw new Error("distanceKm must not exist");
const prompts=[1,2,3,4,5].map(i=>fs.readFileSync(path.join(ROOT,"prompts",`${String(i).padStart(2,"0")}-${["start-province","run-scope","resume","repair-entity","final-audit-minify"][i-1]}.txt`),"utf8"));
const concrete=/\b(?:province|county|city|village|place)-\d+(?:-[A-Za-z0-9_-]+)*\b/;
for(const [i,p] of prompts.entries()) if(concrete.test(p)) throw new Error(`Concrete production id in prompt ${i+1}`);
if(!/province_id=<PROVINCE_ID>/.test(prompts[0])) throw new Error("Prompt 01 missing province_id");
if(!/scope_id=<SCOPE_ID>/.test(prompts[1])) throw new Error("Prompt 02 missing scope_id");
if(!/previous_id=<PREVIOUS_ID>/.test(prompts[2])) throw new Error("Prompt 03 missing previous_id");
if(!/entity_id=<ENTITY_ID>/.test(prompts[3])) throw new Error("Prompt 04 missing entity_id");
if(!/final_audit=true/.test(prompts[4])) throw new Error("Prompt 05 missing final_audit");
const server=read("src/server.ts"); if(server.includes("\"resolve_scope_name\"")) throw new Error("resolve_scope_name must not be registered");
console.log("Planro verification PASS", JSON.stringify({requiredFiles:req.length,provinceInputs:31,taxonomy:t},null,2));
